# Generated by Django 2.2.24 on 2021-08-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiocontent',
            options={'verbose_name': 'Аудио', 'verbose_name_plural': 'Аудио'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='textcontent',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текста'},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
